name: Deploy changes to production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull changes
        run: |
          whoami
          pwd
          cd ${{ secrets.PROJECT_REMOTE_PATH }}
          pwd
          ls
          git pull origin main
          git log
